---
title: "ESM229_HW1"
author: "Juan Espinoza"
date: "1/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
```

Part 0b: Model parameters

```{r}
# Fixed Economic parameters (LEAVE THIS ALONE FOR NOW)
p_saving<-c(.22) # output saved, default at 0.22
p_capShare<-c(.3) # Cobb-Douglas capital share, defaut at 0.3
p_capDep<-c(.1) # capital depreciation, default at 0.1
p_TFP_g<-c(.005) # TFP growth rate, default at 0.005   
p_damage<-c(.009) # default at 0.009

# Variable Economic parameters (TRY DIFFERENT VALUES)
p_emInt_g<-c(-.005) # default at -.005
p_enInt_g<-c(-.01) # default at -.01
p_pop_g<-c(0.01) # default at .01
    
# Fixed climate parameters (LEAVE THIS ALONE)
p_carDecay<-c(400) # carbon decay, default 400
p_climDelay<-c(.015) # climate decay, default 0.015

#Variable climate parameters (TRY DIFFERENT VALUES)
p_climSens<-c(2.5) # climate sensitivity default 2.5
```

Part 0c: Initial Conditions

```{r}
# years
p_years<-c(291)

# Economic
ic_pop<-c(6900) # in millions
ic_enInt<-c(5.98) # in EJ/$trill
ic_emInt<-c(68.27) # in Mt CO2 /EJ            
ic_K<-c(139.65) # $trill   
ic_TFP<-c(.03)

# Climate
ic_preCO2<-c(275) # ppm
ic_nowCO2<-c(380) # ppm
ic_T<-c(0.8) # degree C above preindustrial

# creating empty matrices for storing data
year<-matrix(0,p_years,1)    
pop<-matrix(0, p_years,1)
enInt<-matrix(0, p_years,1)
emInt<-matrix(0, p_years,1)    
TFP<-matrix(0, p_years,1)
Y_gross<-matrix(0, p_years,1)
K<-matrix(0, p_years,1)
gdppc<-matrix(0, p_years,1)
CO2ppm<-matrix(0, p_years,1)
em_MtCO2<-matrix(0,p_years,1)
em_ppm<-matrix(0,p_years,1)
Y_net<-matrix(0,p_years,1)
C<-matrix(0,p_years,1)
C_pc<-matrix(0,p_years,1)
Teq<-matrix(0,p_years,1)
climateDamage<-matrix(0,p_years,1)
```

Part 1 Economic Model

```{r}
#Part 1a: Getting exogenous changes in population, energy intensity, emissions intensity, TFP


# initializing for first period    
year[1]<-2010
pop[1]<-ic_pop
enInt[1]<-ic_enInt    
emInt[1]<-ic_emInt
TFP[1]<-ic_TFP

for (j in 2:p_years) {
year[j]<-year[j-1]+1
pop[j]=pop[j-1]*(1+p_pop_g)
enInt[j]=enInt[j-1]*(1+p_enInt_g)
emInt[j]=emInt[j-1]*(1+p_emInt_g)
TFP[j]=TFP[j-1]*(1+p_TFP_g)
    }

```

Part 1b: Getting gross output, capital, emissions

```{r}
# initializing for first period

#Part 1: Economic model w/o climate damages
K[1]<-ic_K
 Y_gross[1]<-TFP[1]*K[1]^p_capShare*pop[1]^(1-p_capShare)
      
#Part 2: climate model
#CO2 concentration
CO2ppm[1]<-ic_nowCO2                      
T[1]=ic_T

#Part 3: Economic model with climate damages
#climate damages
climateShare<-(p_damage*T[1]^2)/(1+p_damage*T[1]^2) # damage function
climateDamage[1]<-climateShare*Y_gross[1] #climate damages
Y_net[1]<-Y_gross[1]-climateDamage[1] # net of damages output          
C[1]<-Y_net[1]-p_saving*Y_net[1]
C_pc[1]<-(C[1]/pop[1])*1000      

plus_one_ton <- c(0, (1/1000000), rep(0, times= 289)) #plus one ton of CO2

# looping over rest of the years
for (j in 2:p_years) {
      
#Part 1: Economic model w/o climate damages     
#Economic output 
K[j]<-(1-p_capDep)*K[j-1]+p_saving*Y_net[j-1]  #capital accumulation
Y_gross[j]<-TFP[j]*K[j]^p_capShare*pop[j]^(1-p_capShare) #Cobb-Douglas production function
gdppc[j]=Y_gross[j]/pop[j]

#emissions
em_MtCO2[j]<-pop[j]*gdppc[j]*enInt[j]*emInt[j] #Kaya identity
em_ppm[j]<-(em_MtCO2[j]+plus_one_ton[j])/7810 # convert to atmospheric CO2 concentrations
      
#Part 2: climate model     
#CO2 concentration
CO2ppm[j]<-CO2ppm[j-1]+0.5*((em_ppm[j])- (CO2ppm[j-1]-(ic_preCO2))/(p_carDecay)) #CO2 concentration accumulation                             
    
#Radiative forcing
rad_CO2_Wpm2<-5.35*log(CO2ppm[j]/ic_preCO2)

#Converting to temperature  
Teq[j]<-rad_CO2_Wpm2*(p_climSens/(5.3*log(2))) #Equilibrium temperature
T[j]=T[j-1]+p_climDelay*(Teq[j]-T[j-1]) #Transient temperature

#Part 3: Economic model with climate damages
climateShare<-(p_damage*T[j]^2)/(1+p_damage*T[j]^2) # damage function
climateDamage[j]<-climateShare*Y_gross[j] # climate damages
Y_net[j]<-Y_gross[j]-climateDamage[j] # output net of damages          
C[j]<-Y_net[j]-p_saving*Y_net[j] # consumption 
C_pc[j]<-(C[j]/pop[j])*1000 #per capita consumption     
    }
  
```

Plots
```{r}
par(mfrow=c(3,2), mar=c(4,4,2,2))
plot(year[2:j], em_MtCO2[2:j], ylab="Emissions (MtCO2")
plot(year[2:j], CO2ppm[2:j], ylab="CO2 concentrations (ppm)")
plot(year[2:j], T[2:j], ylab="Transient temperature (C)")
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)")
plot(year[2:j], Y_net[2:j], ylab="Net output ($ trillion)")
plot(year[2:j], C_pc[2:j], ylab="Consumption per cap ($ thousand)")
```

```{r}
write.csv(climateDamage,"C:\\Users\\Juan\\Desktop\\BREN\\Second Year\\Winter Quarter\\ESM 229\\climateDamageSim1.csv", row.names = FALSE)
```

```{r}

damages_question_3_BAU <- read_csv("climateDamageBAU.csv") %>%
  rename("BAU" = "V1") %>% 
  sum("BAU")

damages_q3_plus1 <- read_csv("climateDamageSim1.csv") %>%
  rename("plus1" = "V1")

#Take difference between BAU scenario and Simulation
#exported damages_all to a csv -> total climate damage = 5945.924



## damages per millions tons of CO2 
## need damages per tons of CO2
damages_all <- cbind(damages_question_3_BAU*1000000000000, damages_q3_plus1*1000000000000) %>%
  mutate(diff = plus1 - BAU) %>%
  mutate(year = 1:291) %>%
  mutate(SCC_j_1.5 = (1/(1+0.015)^year)*diff,
         SCC_j_3 = (1/(1+0.03)^year)*diff) 
SCC_1.5 <- sum(damages_all$SCC_j_1.5)
SCC_3 <- sum(damages_all$SCC_j_3)

## 1.5% SCC; $252.06497 per ton CO2
## 3% SCC; $30.1699525541407 per ton CO2
```

```{r}
write.csv(damages_all,"C:\\Users\\Juan\\Desktop\\BREN\\Second Year\\Winter Quarter\\ESM 229\\climateDamageAll.csv", row.names = FALSE)
```

Original Model with set paramets no addition of plus one more ton
```{r}
# Fixed Economic parameters (LEAVE THIS ALONE FOR NOW)
    p_saving<-c(.22) # output saved, default at 0.22
    p_capShare<-c(.3) # Cobb-Douglas capital share, defaut at 0.3
    p_capDep<-c(.1) # capital depreciation, default at 0.1
    p_TFP_g<-c(.005) # TFP growth rate, default at 0.005   
    p_damage<-c(.009) # default at 0.009

    # Variable Economic parameters (TRY DIFFERENT VALUES)
    p_emInt_g<-c(-.005) # default at -.005
    p_enInt_g<-c(-.01) # default at -.01
    p_pop_g<-c(0.01) # default at .01
    
    # Fixed climate parameters (LEAVE THIS ALONE)
    p_carDecay<-c(400) # carbon decay, default 400
    p_climDelay<-c(.015) # climate decay, default 0.015

    #Variable climate parameters (TRY DIFFERENT VALUES)
    p_climSens<-c(2.5) # climate sensitivity default 2.5
```

```{r}

 # years
    p_years<-c(291)


 # Economic
    ic_pop<-c(6900) # in millions
    ic_enInt<-c(5.98) # in EJ/$trill
    ic_emInt<-c(68.27) # in Mt CO2 /EJ            
    ic_K<-c(139.65) # $trill   
    ic_TFP<-c(.03)

    # Climate
    ic_preCO2<-c(275) # ppm
    ic_nowCO2<-c(380) # ppm
    ic_T<-c(0.8) # degree C above preindustrial

    # creating empty matrices for storing data
    year<-matrix(0,p_years,1)    
    pop<-matrix(0, p_years,1)
    enInt<-matrix(0, p_years,1)
    emInt<-matrix(0, p_years,1)    
    TFP<-matrix(0, p_years,1)
    Y_gross<-matrix(0, p_years,1)
    K<-matrix(0, p_years,1)
    gdppc<-matrix(0, p_years,1)
    CO2ppm<-matrix(0, p_years,1)
    em_MtCO2<-matrix(0,p_years,1)
    em_ppm<-matrix(0,p_years,1)
    Y_net<-matrix(0,p_years,1)
    C<-matrix(0,p_years,1)
    C_pc<-matrix(0,p_years,1)
    Teq<-matrix(0,p_years,1)
    climateDamage<-matrix(0,p_years,1)
```

```{r}
# initializing for first period    
    year[1]<-2010
    pop[1]<-ic_pop
    enInt[1]<-ic_enInt    
    emInt[1]<-ic_emInt
    TFP[1]<-ic_TFP

    for (j in 2:p_years) {
      year[j]<-year[j-1]+1
      pop[j]=pop[j-1]*(1+p_pop_g)
      enInt[j]=enInt[j-1]*(1+p_enInt_g)
      emInt[j]=emInt[j-1]*(1+p_emInt_g)
      TFP[j]=TFP[j-1]*(1+p_TFP_g)
    }
```

```{r}
 # initializing for first period
    #Part 1: Economic model w/o climate damages
    K[1]<-ic_K
    Y_gross[1]<-TFP[1]*K[1]^p_capShare*pop[1]^(1-p_capShare)
      
    #Part 2: climate model
    #CO2 concentration
    CO2ppm[1]<-ic_nowCO2                      
    T[1]=ic_T

    #Part 3: Economic model with climate damages
    #climate damages
    climateShare<-(p_damage*T[1]^2)/(1+p_damage*T[1]^2) # damage function
    climateDamage[1]<-climateShare*Y_gross[1] #climate damages
    Y_net[1]<-Y_gross[1]-climateDamage[1] # net of damages output          
    C[1]<-Y_net[1]-p_saving*Y_net[1]
    C_pc[1]<-(C[1]/pop[1])*1000   
    
    

```

```{r}
 # looping over rest of the years
    for (j in 2:p_years) {
      
      #Part 1: Economic model w/o climate damages     
      #Economic output 
      K[j]<-(1-p_capDep)*K[j-1]+p_saving*Y_net[j-1]  #capital accumulation
      Y_gross[j]<-TFP[j]*K[j]^p_capShare*pop[j]^(1-p_capShare) #Cobb-Douglas production function
      gdppc[j]=Y_gross[j]/pop[j]

      #emissions
      em_MtCO2[j]<-pop[j]*gdppc[j]*enInt[j]*emInt[j] #Kaya identity
      em_ppm[j]<-em_MtCO2[j]/7810 # convert to atmospheric CO2 concentrations
      
      #Part 2: climate model     
      #CO2 concentration
      CO2ppm[j]<-CO2ppm[j-1]+0.5*((em_ppm[j])- (CO2ppm[j-1]-(ic_preCO2))/(p_carDecay)) #CO2 concentration accumulation                             
    
      #Radiative forcing
      rad_CO2_Wpm2<-5.35*log(CO2ppm[j]/ic_preCO2)

      # Converting to temperature  
      Teq[j]<-rad_CO2_Wpm2*(p_climSens/(5.3*log(2))) #Equilibrium temperature
      T[j]=T[j-1]+p_climDelay*(Teq[j]-T[j-1]) #Transient temperature

      #Part 3: Economic model with climate damages
      climateShare<-(p_damage*T[j]^2)/(1+p_damage*T[j]^2) # damage function
      climateDamage[j]<-climateShare*Y_gross[j] # climate damages
      Y_net[j]<-Y_gross[j]-climateDamage[j] # output net of damages          
      C[j]<-Y_net[j]-p_saving*Y_net[j] # consumption 
      C_pc[j]<-(C[j]/pop[j])*1000 #per capita consumption     
    }
```

```{r}
par(mfrow=c(3,2), mar=c(4,4,2,2))
plot(year[2:j], em_MtCO2[2:j], ylab="Emissions (MtCO2")
plot(year[2:j], CO2ppm[2:j], ylab="CO2 concentrations (ppm)")
plot(year[2:j], T[2:j], ylab="Transient temperature (C)")
plot(year[2:j], Teq[2:j], ylab="Equilibrium temperature (C)")
plot(year[2:j], Y_net[2:j], ylab="Net output ($ trillion)")
plot(year[2:j], C_pc[2:j], ylab="Consumption per cap ($ thousand)")

```

```{r}
write.csv(climateDamage,"C:\\Users\\Juan\\Desktop\\BREN\\Second Year\\Winter Quarter\\ESM 229\\climateDamageBAU2.csv", row.names = FALSE)
```

